# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

matrix:
  include:
    - language: R
      cache: R
    - language: Python
      python: 3.6

before_install:
  - pip install gensim
