language: R
warnings_are_errors: false
cache: packages

before_install:
  - sudo pip install gensim sklearn

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - reticulate

notifications:
  email:
    on_failure: change
