language: R
warnings_are_errors: false
sudo: required
dist: trusty
cache: packages

before_install:
  - pip install gensim sklearn

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - testthat
   - reticulate

notifications:
  email:
    on_failure: change
