# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - sudo apt-get install python3
  - pip3 install gensim sklearn

addons:
  apt:
    update: true