language: R
warnings_are_errors: false
cache: packages

before_install:
  - R -e "install.packages('reticulate')"
  - R -e "reticulate::py_install('gensim')"
  - R -e "reticulate::py_install('scikit-learn')"
  - R -e "reticulate::py_install('pyLDAvis')"

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'covr::codecov()'

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_failure: change
