language: R
warnings_are_errors: false
cache: packages

before_install:
  - R -e "install.package('reticulate')"
  - R -e "reticulate::py_install('gensim')"

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_failure: change
